# Generated by Django 3.2.9 on 2021-12-26 10:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts-images/')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated on')),
            ],
        ),
    ]
