# Generated by Django 3.2.9 on 2021-12-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
    ]
