# Generated by Django 3.2.9 on 2021-12-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
                ('theme', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.theme')),
            ],
        ),
    ]
