# Generated by Django 3.2.9 on 2021-12-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sunday', models.TextField(blank=True, default=None, null=True)),
                ('Monday', models.TextField(blank=True, default=None, null=True)),
                ('Tuesday', models.TextField(blank=True, default=None, null=True)),
                ('Wednesday', models.TextField(blank=True, default=None, null=True)),
                ('Thursday', models.TextField(blank=True, default=None, null=True)),
                ('Friday', models.TextField(blank=True, default=None, null=True)),
                ('Saturday', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
