# Generated by Django 3.2.9 on 2021-12-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Friday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Monday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Sunday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Thursday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Wednesday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.TextField(blank=True, default='dayName', max_length=10, null=True),
        ),
    ]
