# Generated by Django 3.2.9 on 2021-12-26 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories-images/')),
                ('parent', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Theme Name !', max_length=32, null=True)),
                ('title', models.CharField(blank=True, default='Theme Title !', max_length=32, null=True)),
                ('description', models.TextField(blank=True, default='description ...', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories-images/')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
        ),
    ]
