# Generated by Django 3.2.9 on 2022-01-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220105_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='a_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='a_theme',
        ),
    ]
