# Generated by Django 3.2.9 on 2021-12-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_theme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
